export const ADD_TOKEN = 'ADD_TOKEN';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const BOUNTY_ACTIVATED = 'BOUNTY_ACTIVATED';
export const SUBMISSION_ACCEPTED = 'SUBMISSION_ACCEPTED';
export const JOB_SUBMITTED = 'JOB_SUBMITTED';
